services:
  db:
    container_name: postgres_container
    image: postgres:14.2
    ports:
      - 5000:5432
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: Mpampis
      POSTGRES_PASSWORD: db_password
    volumes:
    - ./postgres/data:/var/lib/postgresql/data